all:clean
	xelatex pythonFp.tex
	xelatex pythonFp.tex 
	evince pythonFp.pdf &
clean:
	rm -rf pythonFp.aux pythonFp.idx pythonFp.log pythonFp.pdf pythonFp.toc pythonFp.out pythonFp.snm pythonFp.nav pythonFp.vrb

