all:clean
	xelatex document.tex
	xelatex document.tex 
	evince document.pdf
clean:
	rm -rf document.aux document.idx document.log document.pdf document.toc document.out document.snm document.nav document.vrb

